DROP TABLE IF EXISTS scrape_results CASCADE;
DROP TABLE IF EXISTS cookie_results CASCADE;
DROP TABLE IF EXISTS privacy_results CASCADE;
DROP TABLE IF EXISTS compliance_urls CASCADE;
DROP TABLE IF EXISTS services CASCADE;
